ansible_user: hal

common_packages:
  - curl
  - git
  - htop

managed_users:
  - name: bill
    password: "{{ user_passwords.bill }}"
    state: present
    home: /home/bill
    groups: ['docs', 'media']
  - name: hal
    uid: 1999
    state: present
    groups: ['sudo']
    home: /home/hal

custom_groups:
  - name: media
    gid: 1776
    state: present
  - name: docs
    gid: 1787
    state: present
