ansible_user: hal

common_packages:
  - curl
  - git
  - htop
  - sudo

managed_users:
  - name: bill
    home: /home/bill
    uid: 1000
    groups: sudo, admin
    shell: /bin/bash
    state: present
  - name: hal
    home: /home/hal
    uid: 101
    groups: sudo
    shell: /bin/bash
    state: present
