users:
  - name: bill
    uid: 1000
    groups: sudo, admin
    state: present
  - name: hal
    uid: 101
    groups: sudo, non-login
    shell: /usr/sbin/nologin
    state: present

ansible_user: hal

groups:
  - name: sudo
    state: present

common_packages:
  - curl
  - git
  - htop
  - sudo

