users:
  - name: bill
    uid: 1000
    groups: sudo, admin
    state: present
  - name: hal
    uid: 101
    groups: sudo
    shell: /bin/bash
    state: present

ansible_user: hal

common_packages:
  - curl
  - git
  - htop
  - sudo

