groups:
  - name: media
    gid: 1776
    state: present

mount_points:
  - { mount_point: "mp0: /mnt/media,mp=/mnt/media,backup=0" }
dynamic_container_ids: ["101", "102", "103"] # Adjust as needed
      
users:
  - name: bill
    groups: media, sudo
    state: present
    
  - name: hal
    groups: sudo, media
    shell: /bin/bash
    state: present