custon_groups:
  - name: media
    gid: 1776
    state: present

mount_points:
  - { mount_point: "mp0: /mnt/media,mp=/mnt/media,backup=0" }
dynamic_container_ids: ["101", "102", "103"] # Adjust as needed
      
managed_users:
  - name: bill
    home: /home/bill
    groups: ['sudo', 'docs']
    state: present
  - name: hal
    home: /home/hal
    groups: ['sudo', 'docs']
    shell: /bin/bash
    state: present

users: "{{ managed_users }}"