managed_users:
  - name: bill
    home: /home/bill
    groups: ['sudo', 'media', 'docs']
    state: present
  - name: hal
    home: /home/hal
    groups: ['sudo', 'media', 'docs']
    shell: /bin/bash
    state: present

users: "{{ managed_users }}"

custom_groups:
  - name: git
    gid: 2013
    state: present
  - name: media
    gid: 1776
    state: present
  - name: docs
    gid: 1787
    state: present

fstab_entries:
  mounts:
    - { server: "192.168.86.90", remote_path: "/mnt/ssd-files/docs", path: "/mnt/docs" }
    - { server: "192.168.86.90", remote_path: "/mnt/Data/media", path: "/media" }
