---
- name: Add sudoers files
  tags: always
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0440'
  loop:
    - { src: 'files/sudoer_hal', dest: '/etc/sudoers.d/hal' }
    - { src: 'files/sudoer_bill', dest: '/etc/sudoers.d/bill' }
