---
- name: Ensure directories exist
  file:
    path: "{{ item.local_path }}"
    state: directory
  with_items: "{{ nfs_shares }}"
  when: nfs_shares is defined

- name: Ensure NFS shares are mounted
  mount:
    src: "{{ item.server }}:{{ item.remote_path }}"
    path: "{{ item.local_path }}"
    fstype: nfs
    state: mounted
  with_items: "{{ nfs_shares }}"
  when: nfs_shares is defined
