---
- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: update systems
    tags: always
    package:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: create group git
    tags: always
    ansible.builtin.group:
      name: git
      state: present
      gid: 2013

  - name: create group media
    tags: always
    ansible.builtin.group:
      name: media
      state: present
      gid: 1776

  - name: create group docs
    tags: always
    ansible.builtin.group:
      name: docs
      state: present
      gid: 1787

  - name: create bill user
    tags: always
    user: 
      name: bill
      create_home: yes
      shell: /bin/bash
      groups: sudo,adm,root,git,media,docs
      append: true
      uid: 1000      
 
  - name: create hal user if missing
    tags: always
    user: 
      name: hal
      create_home: yes
      shell: /bin/bash
      groups: sudo,git,media,docs
      uid: 1001

  - name: create user lily
    tags: always
    user: 
      name: lily
      create_home: yes
      shell: /bin/bash
      groups: sudo,docs,media
      uid: 1002

  - name: add ssh key for hal
    tags: always
    authorized_key: 
      user: hal
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDgyiZ4tMW4B6bJ6VNep4e9grqu0Mc8JbDoZsFs3Kd1EYPKMt/p2oS0nH8BeqVgYVZ34AW4Yw42DSYza1upJ7vOOwN0YpjkXoXhW9B9u5caS9IfRjSa4nVCX3eXRY6XpMWfX25BxTZNxI8BT8QihIhX7MDFSO4d/93YcBwnhXenLIe1Mf5Od1B7qbr2j7V4w2VLt1UeRrhrlPnYFawhdm0kllGNL9oFaU0QEvjaect3wBVKVybhDUGIeo5r3Gkt6SctYc69XlJyufWI6eEfptP19rPhTMJzP4W3gIKqNcs/XeiuUeUoWkpLC8Od4DUcl1+VbbIAIX/yjj4MVHk48Uvhpvp3VZ2EcDxLTxV4M6ZQTsTno40w880CJ3uqLFDycjdvBhw1JNQZ4VCLAKi6i3JeH3Gvo8M1a9QNMBbk7/g1qm3mZ3NWLaTltXdnrr/X+/sCVUNWdEaH7fektUMWTl/YtqeivPr4nHDnaJseKxkRwjmemX02YZDS/i++12WwW4c= bill@semaphore"
 
  - name: add ssh key for bill
    tags: always
    authorized_key: 
      user: bill
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOkdzXCp480fWqPU0pMP4BLtrSEG/V399GAXr+Y4ZTVK bill"

  - name: add sudoers file for hal
    tags: always
    copy:
      src: files/sudoer_hal
      dest: /etc/sudoers.d/hal
      owner: root
      group: root
      mode: 0440

  - name: add sudoers file for bill
    tags: always
    copy:
      src: files/sudoer_bill
      dest: /etc/sudoers.d/bill
      owner: root
      group: root
      mode: 0440 

  - name: install packages
    package:
      name:
        - htop
        - tmux
        - vim-nox
        - git
        - mc
        - curl
        - keychain
        - python3-psutil
        - nfs-common
        - software-properties-common
        
  - name: copy wallpaper file
    copy:
      src: files/deep_space_wallpaper.avif
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root
 
  - name: set wallpaper
    become_user: bill
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: bill
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: Ensure bill's home directory exists
    file:
      path: "/home/bill"
      state: directory
      mode: '0755'

  - name: Copy the new user photo to bill's home directory
    copy:
      src: /path/to/new_photo.jpg
      dest: "/home/bill/photo.jpg"
      owner: bill
      group: bill
      mode: '0644'

  - name: Register the new user photo
    command: sudo update-alternatives --install /usr/bin/xdmx-user-photo xdmx-user-photo /home/bill/photo.jpg 100
    when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution_major_version'] == '20'

  - name: Set the new user photo as the default
    command: sudo update-alternatives --set xdmx-user-photo /home/bill/photo.jpg
    when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution_major_version'] == '20'

  - name: Copy the user photo to GNOME user settings directory
    copy:
      src: /home/bill/photo.jpg
      dest: /home/bill/.face
      owner: bill
      group: bill
      mode: '0644'

  - name: Copy the user photo to GNOME user settings icon
    copy:
      src: /home/bill/photo.jpg
      dest: /home/bill/.face.icon
      owner: bill
      group: bill
      mode: '0644'

  - name: Set the user photo for bill using dconf
    community.general.dconf:
      key: /org/gnome/login-screen/logo
      state: present
      value: "'file:///home/bill/photo.jpg'"
    become: false
    become_user: bill

  - name: Refresh GNOME settings
    command: busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting…")'
    become: false
    become_user: bill

    
    #  - name: copy custom .bashrc file
    #   copy:
    #     src: files/bashrc
    #     dest: /home/jay/.bashrc
    #     owner: jay
    #     group: jay
 
  
  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: hal
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/wknight7/auto_cfg.git
