- name: Apply common configurations
  hosts: all
  vars_files:
    - group_vars/common.yml
  roles:
    - common    

- name: Apply group-specific configurations
  hosts: all
  roles:
    - group_specific

- name: Manage LXC containers and clean up fstab entries
  hosts: all
  roles:
    - manage_lxc

- name: Manage directories on workstations
  hosts: workstations
  roles:
    - manage_directories

- name: Manage wallpaper on workstations
  hosts: workstations
  roles:
    - manage_wallpaper

- name: Install software on workstations
  hosts: workstations
  roles:
    - install_software

- name: Manage fstab entries
  hosts: all
  roles:
    - manage_fstab

- name: Manage users and groups
  hosts: all
  roles:
    - manage_users

