---
- name: Ensure Configs directory exists
  file:
    path: "{{ item.home }}/Configs/user_{{ item.name }}"
    state: directory
  become: true
  become_user: "{{ 'bill' if item.name == 'bill' else 'root' }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item
  when: inventory_hostname in groups['workstations']

- name: Set ownership for specific Configs directory
  command: chown {{ item.name }}:{{ item.name }} {{ item.home }}/Configs/user_{{ item.name }}
  become: true
  become_user: "{{ 'bill' if item.name == 'bill' else 'root' }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item
  when: inventory_hostname in groups['workstations']

- name: Set permissions for specific Configs directory
  command: chmod 0755 {{ item.home }}/Configs/user_{{ item.name }}
  become: true
  become_user: "{{ 'bill' if item.name == 'bill' else 'root' }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item
  when: inventory_hostname in groups['workstations']

- name: Copy the new user photo to the home directory
  copy:
    src: files/master_yoda.PNG
    dest: "{{ item.home }}/Configs/user_{{ item.name }}/yoda.PNG"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0644'
  become: true
  become_user: "{{ 'bill' if item.name == 'bill' else 'root' }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item
  when: inventory_hostname in groups['workstations']

- name: Register the new user photo
  command: sudo update-alternatives --install /usr/bin/xdmx-user-photo xdmx-user-photo {{ item.home }}/Configs/user_{{ item.name }}/yoda.PNG 100
  when: ansible_facts['os_family'] == 'Debian' and inventory_hostname in groups['workstations']
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Set the new user photo as the default
  command: sudo update-alternatives --set xdmx-user-photo {{ item.home }}/Configs/user_{{ item.name }}/yoda.PNG
  when: ansible_facts['os_family'] == 'Debian' and inventory_hostname in groups['workstations']
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Copy the user photo to GNOME user settings directory
  copy:
    src: "{{ item.home }}/Configs/user_{{ item.name }}/yoda.PNG"
    dest: "{{ item.home }}/.face"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0644'
    remote_src: yes
  become: true
  become_user: "{{ 'bill' if item.name == 'bill' else 'root' }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item
  when: inventory_hostname in groups['workstations']

- name: Copy the user photo to GNOME user settings icon
  copy:
    src: "{{ item.home }}/Configs/user_{{ item.name }}/yoda.PNG"
    dest: "{{ item.home }}/.face.icon"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0644'
    remote_src: yes
  become: true
  become_user: "{{ 'bill' if item.name == 'bill' else 'root' }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item
  when: inventory_hostname in groups['workstations']

- name: Set the user photo using dconf
  community.general.dconf:
    key: /org/gnome/login-screen/logo
    state: present
    value: "'file://{{ item.home }}/Configs/user_{{ item.name }}/yoda.PNG'"
  become: false
  loop: "{{ users }}"
  loop_control:
    loop_var: item
  when: inventory_hostname in groups['workstations']
