---
- name: Ensure groups are present
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: "{{ item.state }}"
  loop: "{{ custom_groups }}"

- name: Check if hal user exists
  getent:
    database: passwd
    key: hal
  register: hal_user_exists
  ignore_errors: true

- name: Ensure users are present
  user:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    uid: "{{ item.uid | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | join(',') }}"
    password: "{{ item.password | default(omit) }}"
  when: item.name != 'hal'
  loop: "{{ managed_users }}"
  loop_control:
    loop_var: item

- name: Ensure hal user is present if not already
  user:
    name: hal
    uid: 1999
    home: /home/hal
    shell: /bin/bash
    groups: sudo
    state: present
  when: hal_user_exists.failed
