---
- name: Include common variables
  include_vars:
    file: "../../group_vars/common.yml"

- name: Include vault variables
  include_vars:
    file: "../../group_vars/vault.yml"

- name: Ensure custom_groups are present
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: "{{ item.state }}"
  loop: "{{ custom_groups }}"

- name: Ensure all required groups are present
  block:
    - name: Gather all groups
      set_fact:
        all_groups: "{{ managed_users | map(attribute='groups') | flatten | unique }}"
    - name: Ensure each group is present
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ all_groups }}"
