---
- name: Clean up old NFS and CIFS entries in fstab (VM)
  lineinfile:
    path: /etc/fstab
    state: absent
    regex: '^\s*192\.168\.86\.90:.*\s+(nfs|cifs)\s+.*'
    backup: yes
  when: vm_type is defined and vm_type == 'vm'

- name: Clean up old NFS and CIFS entries in fstab (LXC)
  lineinfile:
    path: /etc/fstab
    state: absent
    regex: '^\s*192\.168\.86\.90:.*\s+(nfs|cifs)\s+.*'
    backup: yes
  when: vm_type is not defined or vm_type != 'vm'

- name: Append mountpoints to LXC containers
  block:
    - name: Append mountpoints to LXC containers
      delegate_to: "{{ groups['proxmox'][0] }}"
      lineinfile:
        path: "/etc/pve/lxc/{{ container_id }}.conf"
        line: "{{ item.mount_point }}"
        state: present
      loop: "{{ hostvars[inventory_hostname].mount_points }}"
      loop_control:
        loop_var: item
      when: vm_type is not defined or vm_type != 'vm'

- name: Append fstab entries to VMs
  block:
    - name: Ensure fstab entries are defined
      set_fact:
        fstab_mounts: "{{ fstab_entries.mounts }}"
      when: fstab_entries is defined

    - name: Append fstab mounts
      lineinfile:
        path: /etc/fstab
        line: "{{ item.server }}:{{ item.remote_path }} {{ item.path }} nfs defaults 0 0"
        state: present
      loop: "{{ fstab_mounts }}"
      loop_control:
        loop_var: item
      when: vm_type is defined and vm_type == 'vm'

- name: Restart LXC container
  delegate_to: "{{ groups['proxmox'][0] }}"
  command: pct reboot {{ container_id }}
  when: vm_type is not defined or vm_type != 'vm'

- name: Clean up old NFS and CIFS entries in fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regex: '^\s*192\.168\.86\.90:.*\s+(nfs|cifs)\s+.*'
    backup: yes
  when: fstab_entries is defined

