---
- name: Clean up old NFS and CIFS entries in fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regex: '^\s*192\.168\.86\.90:.*\s+(nfs|cifs)\s+.*'
    backup: yes

- name: Install LXC tools
  apt:
    name: lxc
    state: present
  become: true

- name: Gather LXC container IDs
  command: lxc-ls --fancy --fancy-format name
  register: lxc_container_ids

- name: Set fact for container IDs
  set_fact:
    dynamic_container_ids: "{{ lxc_container_ids.stdout_lines }}"

- name: Ensure mountpoints are appended to LXC containers
  block:
    - name: Append mountpoints
      lineinfile:
        path: "/etc/pve/lxc/{{ item }}.conf"
        line: "{{ mount_points | selectattr('container_id', 'equalto', item) | map(attribute='mount_point') | list | join('\n') }}"
        state: present
      loop: "{{ dynamic_container_ids }}"
      when: dynamic_container_ids is defined

- name: Clean up old NFS and CIFS entries in fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regex: '^\s*192\.168\.86\.90:.*\s+(nfs|cifs)\s+.*'
    backup: yes
  when: fstab_entries is defined

