---
- name: Clean up old NFS and CIFS entries in fstab (LXC)
  lineinfile:
    path: /etc/fstab
    state: absent
    regex: '^\s*192\.168\.86\.90:.*\s+(nfs|cifs)\s+.*'
    backup: yes
  when: vm_type is not defined or vm_type != 'vm'

- name: Check if LXC config file exists
  stat:
    path: "/etc/pve/lxc/{{ hostvars[inventory_hostname].container_id }}.conf"
  register: lxc_config
  when: hostvars[inventory_hostname].container_id is defined

- name: Append mountpoints to LXC containers
  block:
    - name: Append mountpoints to LXC containers
      delegate_to: "{{ groups['proxmox'][0] }}"
      lineinfile:
        path: "/etc/pve/lxc/{{ hostvars[inventory_hostname].container_id }}.conf"
        line: "{{ item.mount_point }}"
        state: present
      loop: "{{ hostvars[inventory_hostname].mount_points }}"
      loop_control:
        loop_var: item
      when:
        - vm_type is not defined or vm_type != 'vm'
        - lxc_config.stat.exists
      register: mountpoints_changed
  when: hostvars[inventory_hostname].container_id is defined

- name: Restart LXC container if changes detected
  delegate_to: "{{ groups['proxmox'][0] }}"
  command: pct reboot {{ hostvars[inventory_hostname].container_id }}
  when:
    - mountpoints_changed is defined and mountpoints_changed.changed
    - vm_type is not defined or vm_type != 'vm'
    - hostvars[inventory_hostname].container_id is defined

