---
- name: Clean up old NFS and CIFS entries in fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regex: '^\s*192\.168\.86\.90:.*\s+(nfs|cifs)\s+.*'
    backup: yes

- name: Install LXC tools
  apt:
    name: lxc
    state: present
  become: true

- name: Gather LXC container IDs
  command: lxc-ls -1
  register: lxc_container_ids_raw

- name: Debug raw container IDs output
  debug:
    var: lxc_container_ids_raw.stdout_lines

- name: Process container IDs
  set_fact:
    dynamic_container_ids: "{{ lxc_container_ids_raw.stdout_lines | map('trim') | reject('equalto', '') | list }}"

- name: Debug processed container IDs
  debug:
    var: dynamic_container_ids

- name: Debug mount points
  debug:
    var: mount_points

- name: Ensure mountpoints are appended to LXC containers
  block:
    - name: Append mountpoints
      lineinfile:
        path: "/etc/pve/lxc/{{ item }}.conf"
        line: "{{ mount_points | selectattr('container_id', 'equalto', item) | map(attribute='mount_point') | list | join('\n') }}"
        state: present
      loop: "{{ dynamic_container_ids }}"
      when: dynamic_container_ids | length > 0

- name: Clean up old NFS and CIFS entries in fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regex: '^\s*192\.168\.86\.90:.*\s+(nfs|cifs)\s+.*'
    backup: yes
  when: fstab_entries is defined
