- name: create group media
  tags: always
  ansible.builtin.group:
    name: media
    state: present
    gid: 1776

- name: add hal to media group
  tags: always
  user:
    name: hal
    groups: media
    append: true

- name: add bill to media group
  tags: always
  user:
    name: bill
    groups: media
    append: true

- name: Gather LXC container facts
  command: lxc-ls --fancy
  register: lxc_containers

- name: Ensure mountpoints are appended to LXC containers
  block:
    - name: Append mountpoints
      lineinfile:
        path: "/etc/pve/lxc/{{ item.container_id }}.conf"
        line: "mp0: /media/storage,mp=/media"
        state: present
      with_items: "{{ lxc_containers.stdout_lines | map('regex_search', '^\\s*([\\d]+)\\s', '\\g<1>') | list }}"
      loop_control:
        loop_var: item